version: '3.8'
networks:
  net:

volumes:
  persistence:
services:
  db:
    image: mysql:latest
    container_name: MySQLCont
    environment:
      - "MYSQL_USER=userExample"
      - "MYSQL_DATABASE=elyteGo"
      - "MYSQL_ROOT_PASSWORD=54321"
      - "MYSQL_PASSWORD=54321"
    ports:
      - "3306:3306"
    volumes:
      - ./persistence:/var/lib/mysql
    healthcheck:
      test: "mysql -u userExample -p54321 db -e 'select 1'"
      timeout: 20s
      interval: 10s
      retries: 10
    networks:
      - net
  migrations:
    depends_on:
      db:
        condition: service_healthy
    image: db.migrations
    build:
      context: ./db-migrations/
      dockerfile: Dockerfile
    command: "'mysql://userExample:54321@tcp(db:3306)/elyteGO' up"

  